---
title: "About"
---

### About this site

This site is made in RMarkdown using three essential components: index.html, _site.yml, and about.html. It is hosted remotely on Github; the source code can be found at this [repo directory](https://github.com/owen633/owen633.github.io).

The Rstudio Version used to make this project is 3.5.1. The packages used are *tidyverse(v1.2.1)*, *viridis*, *plotly*, and the class dataset *p8105.datasets*.

### About the data

The data from which the flexdashboard plotly plots were created is from "NYC Restaurant Inspection Results", in which the DOHMC evaluates each restaurant based on different criteria. Scores are assigned to each of them and converted to letter grades with lower scores corresponding to higher grades.

In order to produce reasonable and readable plotly graphs, I randomly sampled 5000 restaurants of rank A situated solely in Manhattan as a subset from the entire dataset and made a scatterplot, a boxplot, and a bargraph to conduct exploratory analysis of the data visually.